### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by dancinglightning** [jeffwilliams/quartz-flow#2]
Am i understanding this right, you wrote a torrent library in ruby? Great work if you managed that one!

I am having installation issues, probably because you have developed this under 1.9 and without bundler.
The first is 
require': /var/www/vhosts/auringostaitaan.fi/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/quartz_torrent-0.2.0/lib/quartz_torrent/trackerclient.rb:32: invalid multibyte escape: /[\x80-\xff]/ (SyntaxError)

I commented the line and the setup command worked ok.

but when running i get `require': cannot load such file -- haml (LoadError)

and since it is not mentioned in the gemspec i don't know which version to get. I'm guessing it doesn't start with 4

But i would like to get it up, being a ruby fan :-)

**Comment by dancinglightning** [comment]
Tried haml 3.1.8 and it started, good.
But doesn't work, because of the commented out line i guess

**Comment by jeffwilliams** [comment]
Hi Torsten,

> Am i understanding this right, you wrote a torrent library in ruby? Great work if you managed that one!

Thanks! Yes, this gem (quartz-flow) uses a pure ruby torrent library I wrote named quartz-torrent found here: 

  [https://github.com/jeffwilliams/quartz-torrent](https://github.com/jeffwilliams/quartz-torrent)

quartz-flow is a web-based torrent client that uses quartz-torrent for managing the torrents.

> I am having installation issues, probably because you have developed this under 1.9 and without bundler.
> The first is require': /var/www/vhosts/auringostaitaan.fi/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/quartz_torrent-0.2.0/lib/quartz_torrent/trackerclient.rb:32: invalid multibyte escape: /[\x80-\xff]/ 

Yes, I developed it in ruby 1.9, and if you are using ruby 1.8 I think that might be causing the problem. I haven't really tested it with 1.8. I should probably make a note of that and add a minimum ruby version to the gemspec.

> but when running i get `require': cannot load such file -- haml (LoadError)

Oops! Yes that seems to be a dependency that's missing from the gemspec. I'll add that in.

> and since it is not mentioned in the gemspec i don't know which version to get. I'm guessing it doesn't start with 4

Actually, the one I'm using is 4.0.5, so I think the 4.x versions should ideally work...

**Comment by jeffwilliams** [comment]
> Tried haml 3.1.8 and it started, good.
> But doesn't work, because of the commented out line i guess

Hmm, it's possible, but it could be something else. When you start quartz-flow, it should write logs to the log/ subdirectory of the quartz-flow home directory. Is there anything in there that seems related?

**Comment by dancinglightning** [comment]
Maybe you're right, i seem to get a lot of timeouts. I can send the log, but here is a bit

INFO peerclient: Connected to peer 81.106.122.7:58112. Sending handshake.
 INFO peerclient: Connected to peer 84.93.34.176:51413. Sending handshake.
 INFO peerclient: Connected to peer 5.14.130.156:58946. Sending handshake.
 INFO peerclient: Connected to peer 81.139.8.21:12916. Sending handshake.
 INFO peerclient: Connected to peer 82.3.31.118:19938. Sending handshake.
 WARN peerclient: Peer 81.106.122.7:58112 failed handshake: handshake timed out after 1 seconds.
 WARN peerclient: Peer 84.93.34.176:51413 failed handshake: handshake timed out after 1 seconds.

**Comment by jeffwilliams** [comment]
From the logs it looks like it's working. Are you able to connect from your web browser?

**Comment by dancinglightning** [comment]
yes, i can log in

**Comment by dancinglightning** [comment]
I think this is fixed too. I'll close it and rather open a new if something comes up.
