### ISSUE TITLE
restarting does't work

### ISSUE THREAD

**Issue by dancinglightning** [jeffwilliams/quartz-flow#3]
I did as per instructions, just to check i did an empty run: I mean i created the app, started it, logged in, stopped it and try to start it again:

Stopping torrent client
/gems/2.1.0/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:153:in `local': argument out of range (ArgumentError)
	from /gems/2.1.0/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:153:in `next!'
	from /gems/2.1.0/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:153:in `block in read'
	from /gems/2.1.0/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:276:in `with_connection'
	from /gems/2.1.0/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:141:in `read'
	from /gems/2.1.0/gems/dm-core-1.2.1/lib/dm-core/repository.rb:162:in `read'
	from /gems/2.1.0/gems/dm-core-1.2.1/lib/dm-core/collection.rb:1118:in `lazy_load'
	from /gems/2.1.0/gems/dm-core-1.2.1/lib/dm-core/support/lazy_array.rb:409:in `each'
	from /gems/2.1.0/gems/dm-core-1.2.1/lib/dm-core/collection.rb:505:in `each'
	from /gems/2.1.0/gems/quartz_flow-0.0.4/lib/quartz_flow/usagetracker.rb:125:in `fromModel'
	from /gems/2.1.0/gems/quartz_flow-0.0.4/lib/quartz_flow/usagetracker.rb:281:in `loadBucketsFromDatastore'
	from /gems/2.1.0/gems/quartz_flow-0.0.4/lib/quartz_flow/usagetracker.rb:221:in `initialize'
	from /gems/2.1.0/gems/quartz_flow-0.0.4/lib/quartz_flow/torrent_manager.rb:16:in `new'
	from /gems/2.1.0/gems/quartz_flow-0.0.4/lib/quartz_flow/torrent_manager.rb:16:in `initialize'
	from /gems/2.1.0/gems/quartz_flow-0.0.4/lib/quartz_flow/server.rb:90:in `new'
	from /gems/2.1.0/gems/quartz_flow-0.0.4/lib/quartz_flow/server.rb:90:in `block in <class:Server>'
	from /gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1410:in `configure'
	from /gems/2.1.0/gems/quartz_flow-0.0.4/lib/quartz_flow/server.rb:38:in `<class:Server>'
	from /gems/2.1.0/gems/quartz_flow-0.0.4/lib/quartz_flow/server.rb:37:in `<top (required)>'
	from /2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /gems/2.1.0/gems/quartz_flow-0.0.4/bin/quartzflow:126:in `doStart'
	from /gems/2.1.0/gems/quartz_flow-0.0.4/bin/quartzflow:169:in `<top (required)>'
	from /2.1.5/bin/quartzflow:23:in `load'
	from /2.1.5/bin/quartzflow:23:in `<main>'

**Comment by jeffwilliams** [comment]
That's odd. I'm able to run it using the same dm-do-adapter version (1.2.0) and dm-core (1.2.1).

Are you using ruby 2.1?

**Comment by dancinglightning** [comment]
yes 2.1.5
I can switch to 1.9 if you think that's the problem. Must be something like that if it works for you.

**Comment by jeffwilliams** [comment]
It's worth a try. I've not tested it with ruby 2.1.

I'll test it against ruby 2.1 and see if I can reproduce the problem.

**Comment by jeffwilliams** [comment]
I was able to reproduce this with ruby 2.1.5. I'll investigate to see what the cause is.

**Comment by jeffwilliams** [comment]
I think I've isolated the problem. It seems to be an issue with DataMapper in Ruby 2.x. 

I've pushed a new version of quartz-flow and quartz-torrent that should solve the problem. Would you like to try reinstalling both gems and trying again? For the fix to work you'll need to delete your quartz-flow home directory (or make a new one) and run `quartzflow setup` again.

**Comment by dancinglightning** [comment]
I can't see a new gem, the 0.0.4 that is on rubygems.org is over a year old.

If you add a Gemfile one could bundle and run it from inside the checked out (cloned) directory.
I can do that too if you'll merge the pull.

**Comment by jeffwilliams** [comment]
> I can't see a new gem, the 0.0.4 that is on rubygems.org is over a year
> old.
>

Yeah, I didn't end up pushing a new Gem, just changed the repo.


> If you add a Gemfile one could bundle and run it from inside the checked
> out (cloned) directory.
> I can do that too if you'll merge the pull.
>
That sounds great, thanks!

**Comment by dancinglightning** [comment]
As far as i can tell this is fixed.

I sent a pull with the gemfile, so one can develop easier
