### ISSUE TITLE
can't log in

### ISSUE THREAD

**Issue by dancinglightning** [jeffwilliams/quartz-flow#5]
Slight downside of the pull request, i can't log in anymore.

also i have artefacts on the screen, {{error}} tags.

Sorry, don't have time to debug, but if you find it i can easily update and try again.
The vague feeling points towards "too" new versions, you can see in the Gemfile.lock what is used.

**Comment by jeffwilliams** [comment]
It looks like there was a javascript library (AngularJS) missing from the repo. I've added it and pushed, so hopefully it will work now.

**Comment by rubydesign** [comment]
yep can log in.
Great stuff, congratulations.
I decided not to run it on my server just now, but will keep it in mind.

**Comment by jeffwilliams** [comment]
Thanks for the help! :)

**Comment by rubydesign** [comment]
Hey, just in case you're looking to integrate a search into your nice tool:
I just found a nice one, https://getstrike.net/torrents/ which seems to provide quite good (add free) results.
And has an api and a ruby gem for the api.https://github.com/marshallford/strike_api
 easy peasy.

**Comment by jeffwilliams** [comment]
Thanks for the link, I'll check it out.
